const state={data:null,sport:'ALL',view:'home',deferredInstall:null};
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const pct=v=>v==null?'—':`${(Number(v)*100).toFixed(1)}%`;const num=(v,d=1)=>v==null?'—':Number(v).toFixed(d);const money=v=>v==null?'—':`$${Number(v).toFixed(2)}`;
const cls=s=>{s=String(s||'').toUpperCase();return s.includes('VALID')||s==='PLAY'||s==='ACTIVE'?'live':s.includes('BLOCK')||s==='PASS'?'blocked':'testing'};
function filterRows(rows=[]){return state.sport==='ALL'?rows:rows.filter(r=>String(r.sport||r.league||'').toUpperCase()===state.sport)}
function badge(text){return `<span class="badge ${cls(text)}">${esc(text)}</span>`}
function sectionHead(title,note=''){return `<div class="section-head"><h2>${esc(title)}</h2><span>${esc(note)}</span></div>`}
function pickCard(r){return `<article class="card pick-card"><div class="pick-top"><div><div class="league">${esc(r.sport||'SPORT')} · ${esc(r.market||'MARKET')}</div><div class="pick-title">${esc(r.title||r.player||r.selection||'Research candidate')}</div><div class="pick-sub">${esc(r.event||r.matchup||'')} ${r.book?`· ${esc(r.book)}`:''}</div></div><div class="side-pill">${esc(r.side||'WATCH')}</div></div><div class="metric-grid"><div class="metric"><span>Line</span><strong>${esc(r.line??'—')}</strong></div><div class="metric"><span>Model</span><strong>${pct(r.model_probability)}</strong></div><div class="metric"><span>Edge</span><strong>${r.edge==null?'—':`${(Number(r.edge)*100).toFixed(1)}%`}</strong></div><div class="metric"><span>Conf</span><strong>${r.confidence==null?'—':`${num(r.confidence,0)}`}</strong></div></div><div class="status-line"><div>${badge(r.status||r.validation_status||'WATCHLIST')}</div><div class="status-copy">${esc(r.note||r.readiness||'Research only')}</div></div></article>`}
function comboCard(c){const legs=(c.legs||[]).map(l=>`<div class="combo-leg"><div><strong>${esc(l.title||l.player||l.selection||'Leg')}</strong><br><span>${esc(l.sport||'')} · ${esc(l.market||'')}</span></div><strong>${esc(l.side||'')}</strong></div>`).join('');return `<article class="card combo-card"><div class="pick-top"><div><div class="league">${esc(c.type||'COMBO')}</div><div class="pick-title">${esc(c.title||'Research combo')}</div></div>${badge(c.status||'WATCHLIST')}</div><div class="combo-legs">${legs||'<div class="muted tiny">No eligible legs.</div>'}</div><div class="status-line"><span class="status-copy">Correlation: ${esc(c.correlation||'—')}</span><strong>${c.expected_value==null?'—':`EV ${(Number(c.expected_value)*100).toFixed(1)}%`}</strong></div></article>`}
function home(){const d=state.data;const plays=filterRows(d.selections||[]).slice(0,3);const watch=filterRows(d.watchlist||[]).slice(0,3);return `${sectionHead('Top Research','latest bundle')}<div class="notice">Selections are not promoted to official plays unless their validation gates are earned. Live ingestion can be active while wagering remains disabled.</div><div class="grid">${plays.length?plays.map(pickCard).join(''):'<div class="empty card"><strong>No validated plays yet.</strong><p>The system is live-testing and accumulating evidence.</p></div>'}</div>${sectionHead('Watchlist',`${watch.length} shown`)}<div class="grid">${watch.length?watch.map(pickCard).join(''):'<div class="empty card"><p>No watchlist rows for this filter.</p></div>'}</div>`}
function picks(){const d=state.data;const rows=[...filterRows(d.selections||[]),...filterRows(d.watchlist||[])];return `${sectionHead('Singles & Props',`${rows.length} markets`)}<div class="grid">${rows.length?rows.map(pickCard).join(''):'<div class="empty card"><strong>No markets available.</strong><p>Change the sport filter or refresh.</p></div>'}</div>${sectionHead('DFS Higher / Lower','PrizePicks & Underdog style')}<div class="grid">${filterRows(d.dfs||[]).length?filterRows(d.dfs||[]).map(pickCard).join(''):'<div class="empty card"><p>DFS lines will appear here when compliant inputs are available.</p></div>'}</div>`}
function combos(){const rows=filterRows(state.data.combos||[]);return `${sectionHead('3-Man / 6-Man','correlation-aware')}<div class="grid">${rows.length?rows.map(comboCard).join(''):'<div class="empty card"><strong>No qualified combos.</strong><p>Combo construction remains blocked until enough validated, low-dependency legs exist.</p></div>'}</div>`}
function performance(){const p=state.data.performance||{};const rows=[['Tracked selections',p.tracked],['Win rate',p.win_rate==null?'—':pct(p.win_rate)],['ROI',p.roi==null?'—':pct(p.roi)],['Yield',p.yield==null?'—':pct(p.yield)],['CLV',p.clv==null?'—':pct(p.clv)],['Settled units',p.units==null?'—':num(p.units,2)],['Bankroll',p.bankroll==null?'—':money(p.bankroll)]];return `${sectionHead('Performance','settled evidence only')}<article class="card performance-card">${rows.map(([a,b])=>`<div class="perf-row"><span>${esc(a)}</span><strong>${esc(b??'—')}</strong></div>`).join('')}</article>${sectionHead('Validation','model maturity')}<article class="card performance-card">${(state.data.validation||[]).map(v=>`<div class="perf-row"><span>${esc(v.sport)} · ${esc(v.market||'all markets')}</span><strong class="${cls(v.status)==='live'?'good':'warn'}">${esc(v.status)}</strong></div>`).join('')||'<div class="muted tiny">Validation evidence will populate as samples settle.</div>'}</article>`}
function system(){const d=state.data;const rows=(d.system||[]).map(x=>`<div class="system-row"><span>${esc(x.label)}</span><strong class="${cls(x.status)==='live'?'good':cls(x.status)==='blocked'?'bad':'warn'}">${esc(x.status)}</strong></div>`).join('');return `${sectionHead('System Status','V2 architecture')}<article class="card system-card">${rows}</article>${sectionHead('Live Test Receipt','provider provenance')}<article class="card system-card"><div class="system-row"><span>Event</span><strong>${esc(d.live_test?.event||'—')}</strong></div><div class="system-row"><span>Markets</span><strong>${esc((d.live_test?.markets||[]).join(', '))}</strong></div><div class="system-row"><span>Capture</span><strong class="good">${esc(d.live_test?.status||'—')}</strong></div><div class="system-row"><span>Credits used</span><strong>${esc(d.live_test?.credits_used??'—')}</strong></div><div class="system-row"><span>Provider balance</span><strong>${esc(d.live_test?.remaining_credits??'—')}</strong></div></article><div class="notice">Publication and wagering actions remain disabled. This interface is a research dashboard, not an automated betting client.</div>`}
function render(){const d=state.data;if(!d)return;$('#modeBadge').textContent=d.meta?.mode||'RESEARCH';$('#modeBadge').className=`badge ${cls(d.meta?.mode)}`;$('#updatedAt').textContent=d.meta?.updated_label||'Updated recently';$('#heroTitle').textContent=d.meta?.headline||'Daily intelligence, one screen.';$('#heroSubtitle').textContent=d.meta?.subtitle||'Research dashboard';$('#qualifiedCount').textContent=(d.selections||[]).length;$('#watchCount').textContent=(d.watchlist||[]).length;$('#sportCount').textContent=(d.meta?.sports||[]).length;const sports=['ALL',...(d.meta?.sports||[])];$('#sportFilters').innerHTML=sports.map(s=>`<button class="chip ${state.sport===s?'active':''}" data-sport="${esc(s)}">${esc(s)}</button>`).join('');$$('.chip').forEach(b=>b.onclick=()=>{state.sport=b.dataset.sport;render()});$('#view-home').innerHTML=home();$('#view-picks').innerHTML=picks();$('#view-combos').innerHTML=combos();$('#view-performance').innerHTML=performance();$('#view-system').innerHTML=system();}
async function load(){try{const r=await fetch(`data.json?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw Error('data unavailable');state.data=await r.json();render();}catch(e){if(!state.data)$('#view-home').innerHTML='<div class="empty card"><strong>Offline</strong><p>The app shell is available, but the latest research bundle could not be loaded.</p></div>';}}
$$('.nav-btn').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;$$('.nav-btn').forEach(x=>x.classList.toggle('active',x===b));$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${state.view}`));window.scrollTo({top:0,behavior:'smooth'})});$('#refreshBtn').onclick=load;
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.deferredInstall=e;$('#installSheet').hidden=false});
$('#installBtn').onclick=async()=>{if(state.deferredInstall){state.deferredInstall.prompt();await state.deferredInstall.userChoice;state.deferredInstall=null;$('#installSheet').hidden=true}else{$('#installCopy').textContent='On iPhone: tap Share in Safari, then choose “Add to Home Screen.”';$('#installBtn').textContent='Got it'}};$('#dismissInstall').onclick=()=>{$('#installSheet').hidden=true;localStorage.setItem('de-install-dismissed','1')};
if(/iPhone|iPad|iPod/.test(navigator.userAgent)&&!navigator.standalone&&!localStorage.getItem('de-install-dismissed'))setTimeout(()=>{$('#installCopy').textContent='On iPhone: tap Share in Safari, then choose “Add to Home Screen.”';$('#installBtn').textContent='Show me';$('#installSheet').hidden=false},1400);
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));load();